
// Sample job listings data
export const job_listings = [
  {
    id: "hvac-1",
    title: "HVAC Design Engineer",
    role: "Engineering",
    location: "Chennai, India",
    experience: "5+ years Experience",
    experienceLevel: "Mid-Senior Level",
    description: "We are looking for an experienced HVAC Design Engineer to join our team in Chennai. The ideal candidate will have expertise in designing HVAC systems for commercial and residential buildings.",
    department: "Engineering & Design",
    employmentType: "Full-time",
    postedDate: "May 15, 2025",
    responsibilities: [
      "Design HVAC systems for various projects including commercial, residential, and industrial buildings",
      "Perform heat load calculations and equipment selection",
      "Create detailed drawings and specifications using CAD software",
      "Coordinate with other engineering disciplines to ensure system integration",
      "Review shop drawings and submittals for compliance with design intent",
      "Participate in client meetings and presentations",
    ],
    requirements: [
      "Bachelor's degree in Mechanical Engineering or related field",
      "5+ years of experience in HVAC design",
      "Proficiency in AutoCAD, Revit MEP, or similar design software",
      "Knowledge of ASHRAE standards and local building codes",
      "Strong analytical and problem-solving skills",
      "Excellent communication and teamwork abilities",
    ],
  },
  {
    id: "plumb-1",
    title: "Plumbing Design Engineer",
    role: "Engineering",
    location: "Chennai, India",
    experience: "5+ years Experience",
    experienceLevel: "Mid-Senior Level",
    description: "Join our team as a Plumbing Design Engineer to develop innovative plumbing solutions for various building types. You'll work with a collaborative team to ensure optimal system performance.",
    department: "Engineering & Design",
    employmentType: "Full-time",
    postedDate: "May 14, 2025",
    responsibilities: [
      "Design plumbing systems for various building types",
      "Perform fixture count calculations and pipe sizing",
      "Create detailed drawings and specifications using CAD software",
      "Coordinate with other disciplines to ensure proper system integration",
      "Review shop drawings and submittals",
      "Conduct site visits to assess existing conditions and verify installations",
    ],
    requirements: [
      "Bachelor's degree in Mechanical or Civil Engineering",
      "5+ years of experience in plumbing system design",
      "Proficiency in AutoCAD, Revit, or similar design software",
      "Knowledge of International Plumbing Code and local regulations",
      "Experience with rainwater harvesting and water conservation systems",
      "Strong problem-solving skills and attention to detail",
    ],
  },
  {
    id: "bim-hvac-1",
    title: "BIM Modeler - HVAC",
    role: "BIM / CAD",
    location: "Chennai, India",
    experience: "5+ years Experience",
    experienceLevel: "Mid-Level",
    description: "We're seeking a skilled BIM Modeler specializing in HVAC systems to join our Chennai office. You'll create detailed 3D models and coordinate with engineering teams to ensure accurate building information models.",
    department: "BIM & Modeling",
    employmentType: "Full-time",
    postedDate: "May 12, 2025",
    responsibilities: [
      "Create detailed 3D BIM models for HVAC systems",
      "Coordinate with engineering teams to ensure accurate representation of systems",
      "Perform clash detection and resolve conflicts within the model",
      "Generate drawing sets from BIM models",
      "Maintain BIM libraries and standards",
      "Participate in BIM coordination meetings",
    ],
    requirements: [
      "3+ years of experience in HVAC BIM modeling",
      "Proficiency in Revit MEP and Navisworks",
      "Understanding of HVAC systems and components",
      "Knowledge of BIM standards and workflows",
      "Ability to work in a team environment",
      "Strong attention to detail and problem-solving skills",
    ],
  },
  {
    id: "bim-plumb-1",
    title: "BIM Modeler - Plumbing",
    role: "BIM / CAD",
    location: "Chennai, India",
    experience: "5+ years Experience",
    experienceLevel: "Mid-Level",
    description: "Join our BIM team as a Plumbing BIM Modeler to create detailed 3D models of plumbing systems for various projects. Work collaboratively to ensure high-quality deliverables.",
    department: "BIM & Modeling",
    employmentType: "Full-time",
    postedDate: "May 12, 2025",
    responsibilities: [
      "Create detailed 3D BIM models for plumbing systems",
      "Coordinate with engineering teams to ensure accurate model development",
      "Perform clash detection and resolve conflicts",
      "Generate drawing sets from BIM models",
      "Maintain BIM libraries and standards",
      "Assist in developing plumbing system layouts",
    ],
    requirements: [
      "3+ years of experience in plumbing BIM modeling",
      "Proficiency in Revit MEP and Navisworks",
      "Understanding of plumbing systems and components",
      "Knowledge of BIM standards and workflows",
      "Ability to work effectively in a team environment",
      "Strong attention to detail and problem-solving skills",
    ],
  },
  {
    id: "bim-elec-1",
    title: "BIM Modeler - Electrical",
    role: "BIM / CAD",
    location: "Chennai, India",
    experience: "5+ years Experience",
    experienceLevel: "Mid-Level",
    description: "We are looking for an experienced BIM Modeler with electrical systems expertise to join our Chennai office. You'll create detailed models and coordinate with our engineering teams.",
    department: "BIM & Modeling",
    employmentType: "Full-time",
    postedDate: "May 11, 2025",
    responsibilities: [
      "Create detailed 3D BIM models for electrical systems",
      "Coordinate with engineering teams to ensure accurate model development",
      "Perform clash detection and resolve conflicts",
      "Generate drawing sets from BIM models",
      "Maintain BIM libraries and standards for electrical components",
      "Assist in developing electrical system layouts",
    ],
    requirements: [
      "3+ years of experience in electrical BIM modeling",
      "Proficiency in Revit MEP and Navisworks",
      "Understanding of electrical systems and components",
      "Knowledge of BIM standards and workflows",
      "Ability to work effectively in a team environment",
      "Strong attention to detail and problem-solving skills",
    ],
  },
  {
    id: "bim-arch-1",
    title: "BIM Modeler - Architectural",
    role: "BIM / CAD",
    location: "Chennai, India",
    experience: "5+ years Experience",
    experienceLevel: "Mid-Level",
    description: "Join our BIM team as an Architectural BIM Modeler to create detailed 3D models of building components. Work with architects and engineers to develop comprehensive building information models.",
    department: "BIM & Modeling",
    employmentType: "Full-time",
    postedDate: "May 10, 2025",
    responsibilities: [
      "Create detailed architectural BIM models",
      "Develop building components, including walls, floors, ceilings, and façades",
      "Coordinate with other disciplines to ensure integrated models",
      "Generate drawing sets from BIM models",
      "Maintain BIM libraries and standards for architectural elements",
      "Assist in space planning and layout development",
    ],
    requirements: [
      "3+ years of experience in architectural BIM modeling",
      "Proficiency in Revit Architecture and Navisworks",
      "Understanding of building systems and construction methods",
      "Knowledge of BIM standards and workflows",
      "Ability to work effectively in a team environment",
      "Strong attention to detail and visualization skills",
    ],
  },
  {
    id: "dry-util-1",
    title: "Dry Utilities Design Engineer",
    role: "Engineering",
    location: "Cairo, Egypt",
    experience: "8+ years Experience",
    experienceLevel: "Senior Level",
    description: "We are seeking an experienced Dry Utilities Design Engineer to join our Cairo team. You'll design electrical distribution, telecom, and gas systems for infrastructure projects.",
    department: "Engineering & Design",
    employmentType: "Full-time",
    postedDate: "May 9, 2025",
    responsibilities: [
      "Design electrical distribution, telecommunication, and gas utility systems",
      "Coordinate with utility companies and government agencies",
      "Prepare engineering calculations and design drawings",
      "Develop technical specifications and bid documents",
      "Perform field investigations and site assessments",
      "Review contractor submittals and RFIs",
    ],
    requirements: [
      "Bachelor's degree in Electrical or Civil Engineering",
      "8+ years of experience in dry utility design",
      "Proficiency in AutoCAD Civil 3D",
      "Knowledge of local utility standards and regulations",
      "Experience with infrastructure and land development projects",
      "Strong communication and coordination skills",
    ],
  },
  {
    id: "wet-util-1",
    title: "Wet Utilities Design Engineer",
    role: "Engineering",
    location: "Cairo, Egypt",
    experience: "8+ years Experience",
    experienceLevel: "Senior Level",
    description: "Join our Cairo office as a Wet Utilities Design Engineer to design water, wastewater, and stormwater systems for infrastructure projects throughout Egypt and the Middle East.",
    department: "Engineering & Design",
    employmentType: "Full-time",
    postedDate: "May 8, 2025",
    responsibilities: [
      "Design water distribution, wastewater collection, and stormwater management systems",
      "Perform hydraulic calculations and system modeling",
      "Prepare engineering drawings and specifications",
      "Coordinate with regulatory agencies and project stakeholders",
      "Conduct site inspections and field investigations",
      "Review contractor submittals and provide technical support during construction",
    ],
    requirements: [
      "Bachelor's degree in Civil or Environmental Engineering",
      "8+ years of experience in wet utility design",
      "Proficiency in AutoCAD Civil 3D and hydraulic modeling software",
      "Knowledge of local and international water/wastewater standards",
      "Experience with infrastructure and land development projects",
      "Strong analytical and problem-solving skills",
    ],
  },
  {
    id: "senior-qs-1",
    title: "Senior QS",
    role: "Quantity Surveying",
    location: "Al Ain, UAE",
    experience: "15+ years Experience",
    experienceLevel: "Senior Level",
    description: "We're looking for a Senior Quantity Surveyor to join our Al Ain office. You'll oversee cost planning and financial management for major construction projects across the UAE.",
    department: "Quantity Surveying",
    employmentType: "Full-time",
    postedDate: "May 7, 2025",
    responsibilities: [
      "Prepare detailed cost estimates and bills of quantities",
      "Conduct tender analysis and prepare tender reports",
      "Administer construction contracts and manage change orders",
      "Prepare monthly payment certificates",
      "Perform cost analysis and value engineering",
      "Manage claim evaluations and final account settlements",
    ],
    requirements: [
      "Bachelor's degree in Quantity Surveying or related field",
      "15+ years of experience as a Quantity Surveyor",
      "Professional qualification (RICS or equivalent)",
      "Experience with major construction projects in the UAE",
      "Knowledge of local construction costs and market conditions",
      "Strong negotiation and contract management skills",
    ],
  },
  {
    id: "struct-draft-1",
    title: "Structural Draftsman",
    role: "CAD / Drafting",
    location: "Al Ain, UAE",
    experience: "6+ years Experience",
    experienceLevel: "Mid-Level",
    description: "Join our Al Ain team as a Structural Draftsman to prepare detailed structural drawings for various construction projects. Work closely with engineers to ensure accurate documentation.",
    department: "Structural Engineering",
    employmentType: "Full-time",
    postedDate: "May 6, 2025",
    responsibilities: [
      "Prepare detailed structural drawings based on engineering calculations",
      "Create foundation plans, framing plans, sections, and connection details",
      "Coordinate with other disciplines to resolve conflicts",
      "Check drawings for accuracy and completeness",
      "Maintain drawing standards and document control",
      "Assist with site inspections and field measurements",
    ],
    requirements: [
      "Diploma or degree in Civil/Structural Engineering or related field",
      "6+ years of experience in structural drafting",
      "Proficiency in AutoCAD and Revit Structure",
      "Understanding of structural systems and construction practices",
      "Knowledge of building codes and standards",
      "Strong attention to detail and organization skills",
    ],
  },
  {
    id: "elec-eng-1",
    title: "Electrical Design Engineer",
    role: "Engineering",
    location: "Abu Dhabi, UAE",
    experience: "5+ years Experience",
    experienceLevel: "Mid-Senior Level",
    description: "We are seeking an Electrical Design Engineer for our Abu Dhabi office to design electrical systems for commercial, residential, and industrial projects.",
    department: "Engineering & Design",
    employmentType: "Full-time",
    postedDate: "May 5, 2025",
    responsibilities: [
      "Design electrical power distribution, lighting, and low voltage systems",
      "Perform load calculations and equipment sizing",
      "Create detailed drawings and specifications using CAD software",
      "Coordinate with other engineering disciplines",
      "Review shop drawings and submittals",
      "Conduct site visits and inspect installations",
    ],
    requirements: [
      "Bachelor's degree in Electrical Engineering",
      "5+ years of experience in electrical systems design",
      "Proficiency in AutoCAD, Revit MEP, or similar software",
      "Knowledge of international electrical codes and standards",
      "Experience with power systems, lighting design, and low voltage systems",
      "Strong analytical and problem-solving skills",
    ],
  },
  {
    id: "mech-eng-1",
    title: "Mechanical Design Engineer",
    role: "Engineering",
    location: "Abu Dhabi, UAE",
    experience: "5+ years Experience",
    experienceLevel: "Mid-Senior Level",
    description: "Join our Abu Dhabi team as a Mechanical Design Engineer to design HVAC, plumbing, and fire protection systems for diverse building projects throughout the UAE.",
    department: "Engineering & Design",
    employmentType: "Full-time",
    postedDate: "May 4, 2025",
    responsibilities: [
      "Design HVAC, plumbing, and fire protection systems",
      "Perform load calculations and equipment selection",
      "Create detailed drawings and specifications",
      "Coordinate with other engineering disciplines",
      "Review shop drawings and technical submittals",
      "Conduct site visits and provide technical support during construction",
    ],
    requirements: [
      "Bachelor's degree in Mechanical Engineering",
      "5+ years of experience in mechanical systems design",
      "Proficiency in AutoCAD, Revit MEP, or similar software",
      "Knowledge of ASHRAE standards and international building codes",
      "Experience with energy-efficient system design",
      "Strong analytical and communication skills",
    ],
  },
];
